export const SHORTCUTS = {
	HELP: '?',
	NEW_POST: 'Alt+N',
	NEW_WRITING_SESSION: 'Alt+W',
	EXPORT_AS_IMAGE: 'Alt+I',
	EXPORT_AS_MARKDOWN: 'Alt+D',
	FOCUS_MODE: 'Alt+M',
	RESET_EDITOR: 'Alt+R',
	PREFERENCES: 'Alt+P',
}
